### ISSUE TITLE
Rule color changing on new line with changed text color

### ISSUE THREAD

**Issue by krumeich** [zauguin/luaul#10]
Consider this MWE:

````
\documentclass{article}

\usepackage{lua-ul}
\usepackage{color}

\begin{document}

\underLine{This is a very long line that is supposed to break and wrap
  around. The color of the underline should be the default color throughout
  \textcolor{blue}{the whole text. However, if I switch the text color to blue,
    then the underline starts in blue on the next line.}}

\end{document}
````

Not sure whether this is a bug or a feature. What I would like is that the color of the underline stays the same throughout the whole underlined passage. Any chance of fixing this?

Thank you for your time and the excellent package that you provide. This might be an edge case, but I really appreciate being able to underline while striking through at the same time.

**Comment by zauguin** [comment]
All color related functionality in the package is designed under the assumption that it's used with `luacolor`, so whithout `luacolor` the interaction with colors is mostly undefined. Since I don't see any reason not to use `luacolor` in LuaLaTeX, there are no place for changing this.

So the fix is simple: Load `luacolor`.

```latex
\documentclass{article}

\usepackage{lua-ul}
\usepackage{luacolor}

\begin{document}

\underLine{This is a very long line that is supposed to break and wrap
  around. The color of the underline should be the default color throughout
  \textcolor{blue}{the whole text. However, if I switch the text color to blue,
    then the underline starts in blue on the next line.}}

\end{document}
```
![image](https://user-images.githubusercontent.com/962229/126194636-df12c9ad-ac4a-47c7-a157-9eb8c8689edf.png)

**Comment by krumeich** [comment]
This is perfect, thank you. I didn't know about luacolor. 

Before closing this issue, permit me one more question: Are there any other packages for Lua(La)TeX that serve as drop-in replacements for more traditional packages? Is there even a comprehensive list of those packages? 

Anway, thanks again!

**Comment by zauguin** [comment]
> Are there any other packages for Lua(La)TeX that serve as drop-in replacements for more traditional packages?

You could argue that `luainputenc` is a drop-in replacement for `inputenc`, but you shouldn't use either one of them so it's not really a good example.

In general drop in replacements are rather uncommon (after all the motivation to create a new package only to duplicate existing functionality is rather low). Also `luacolor` does not really replace `color`, it only provides a different backend. So you usually load both of them (often implicitly since `luacolor` automatically loads `color` if it isn't loaded already). E.g. if you want to use `xcolor` with `luacolor`, you can just load both.

**Comment by krumeich** [comment]
Excellent, thank you for this explanation.
