### ISSUE TITLE
Failure to underline blank space with \par following the underLine command

### ISSUE THREAD

**Issue by atxy-blip** [zauguin/luaul#13]
Hello! I'm working with @FengChendian in a recent LaTeX project. It is proved that the latest version of `luatex-ja` successfully fixed the issue with Chinese underlining, and please accept my gratitude for your efforts.

However, there is one thing that remains. In the template I used to follow the underlined text right with `\par` to force a line break, like the MWE below shows:

```
\documentclass{article}
\usepackage{lua-ul}
\begin{document}
Here is some text: \underLine{This is a long message. It must be awfully long, so long that it can't be contained in one single line.\hfill}\par
The following text.
\end{document}
```

It will be noticed that in this example `\hfill` failed to extend the underline to the end of line.

In the end I have to add an extra `\hspace{0em}` to protect the `\par` command, like this:

```
\documentclass{article}
\usepackage{lua-ul}
\begin{document}
Here is some text: \underLine{This is a long message. It must be awfully long, so long that it can't be contained in one single line.\hfill}\hspace{0em}\par
The following text.
\end{document}
```

And moving `\par` to a new line would save the format in English context, but not with Chinese.

So I am concerned whether `\par` would make the package misjudge the length of underline. I hope this could do some help in the improvement of the package.

**Comment by zauguin** [comment]
I'm not sure if this can be avoided.

`\par` always removes a previous glue (like `\hfill` or a space) in order to avoid having spaces at the end of the line (otherwise separating paragraphs with two linebreaks would always add a space at the end of the paragraph, which is particularly bad since this space would be a potential breakpoint, leading to an empty line if the last line would be almost full). Therefore the `\hfill` gets removed before lua-ul can see it. The only way to avoid this would be for `\par` not to remove previous glue (but that would lead to empty lines) or for some node coming in between to "hide" the glue (e.g. your additional `\hspace{...}`/`\null`/...). All this can't be done by lua-ul it by design does not influence (horizontal) spacing and linebreaking.
Also it reintroduces the issue of empty lines when the space becomes a breakpoint.

Do you have an example of where you need this?

**Comment by atxy-blip** [comment]
For your information, I used to draw the underline in Chinese with `xeCJKfntef` package, which patches the original `uline` command with `xeCJK` engine. And this solution works fine, so fine that when it comes to adding support for LuaTeX, I simply changed `uline` to `underLine` and expected the same result, only to run into the above-mentioned problem.

Here's an MWE to illustrate the effect of `xeCJKfntef`. Note that the `ctexart` class has embedded `xeCJK` support.

```
\documentclass{ctexart}
\usepackage{xeCJKfntef}
\begin{document}
Here is some Chinese text: \uline{这是一句非常非常长的话。非常非常长是有多长呢？反正一行放不下。\hfill}\par
The following text.
\end{document}
```

> Do you have an example of where you need this?

Surely. In the recent project, which is the template for our university's thesis paper, it is officially required that the title should be presented on the abstract page with the same style as my MWE shows: the text "The title is: " followed by the title itself, taking two lines and underlined to the end of line. Presumably, the length of the lines are fixed and could be achieved by `\hrule`, but I found it hard to adjust their relative position with the text and decided to take the underlined `\hfill` measure.

**Comment by zauguin** [comment]
> I simply changed `uline` to `underLine` and expected the same result

`ulem` generally has much more influence on linebreaking then `lua-ul` (e.g. disabling hyphenation, suppressing line breaks in macros, suppressing kerning and ligatures at the start and end), so getting the same result is rather unlikely. Therefore `ulem` can act much earlier before LaTeX removes the space, while luaul only operates after the space is removed.

I think the best solution is to just add `\null` at the end to preserve the space.

**Comment by atxy-blip** [comment]
> I think the best solution is to just add `\null` at the end to preserve the space.

Thanks very much. I believe this totally works for my problem.
