### ISSUE TITLE
Changing color

### ISSUE THREAD

**Issue by Niccori250k** [zauguin/luaul#14]
I'm trying to define underwave command written using TikZ. However, the source below doesn't work though it seems to work correctly.
```tex
\documentclass{article}
\usepackage{lua-ul}
\usepackage{tikz}

\newcommand{\mycolor}{}

\newunderlinetype\beginUnderWavy{\cleaders\hbox to 1.5708ex{%
\hss
\begin{tikzpicture}[x=.25ex,y=.25ex,baseline=.9ex,xscale=1.5708]
\draw[color=\mycolor] (0,0) sin (1,1) cos (2,0) sin (3,-1) cos (4,0);
\end{tikzpicture}%
}}

\NewDocumentCommand\uwave{O{black} +m}{\renewcommand{\mycolor}{#1}{\beginUnderWavy#2}}
\begin{document}\noindent
\uwave{black underwave?}\\
\uwave[red]{red underwave?}\\
\renewcommand{\mycolor}{black}
\begin{tikzpicture}[x=.25ex,y=.25ex,baseline=.9ex,xscale=1.5708]
\draw[color=\mycolor] (0,0) sin (1,1) cos (2,0) sin (3,-1) cos (4,0);
\end{tikzpicture}\\
\renewcommand{\mycolor}{red}
\begin{tikzpicture}[x=.25ex,y=.25ex,baseline=.9ex,xscale=1.5708]
\draw[color=\mycolor] (0,0) sin (1,1) cos (2,0) sin (3,-1) cos (4,0);
\end{tikzpicture}
\end{document}
```
![image](https://user-images.githubusercontent.com/54626227/180976871-03f2b742-a249-4610-986e-1a6958b667e5.png)

**Comment by zauguin** [comment]
Since your underline has to be regenerated whenever `\mycolor` changes, you have to add it to the `context` (the optional argument of `\newunderlinetype`) Since you also use `ex` you also have to include the value of `1ex` there (given that it changes with the fontsize). (1ex is present by default, but if you change it you have to include it).

So you need something like

```
\newunderlinetype\beginUnderWavy[\mycolor!\number\dimexpr 1ex\relax]{\cleaders...
```

**Comment by Niccori250k** [comment]
That wotked correctly! Thank you for answering.
