### ISSUE TITLE
Hope to add double underlines (uuline) and wavy lines to the default commands

### ISSUE THREAD

**Issue by Mikachu2333** [zauguin/luaul#23]
As the title shows.

These two commands are very common when used. Have you considered adding them to the default command set that comes with the macro package without the need for user customization?

**Comment by zauguin** [comment]
The idea in LuauL is really more to provide infrastructure which then allows to define custom commands, so adding more builtins is not really on the roadmap.

More specifically:
 * Double underline: Double underlines are ... two underlines. We could add a default command to do this by default, but just nesting two underlines in a macro is way more flexible than almost anything that could be predefined.
   This is especially important since there is a lot of variation in requirements: How high should the lines be? How thick? Should they have the same thickness? Should they have the same color? Should one of them be a wave? Should both?
 * Wavy lines have even more flexibility (Color, height, width, smooth vs sharp, PDF curve segments or font characters? If not font characters, which graphics package to load to implement PDF curves? How to handle it if the text width is not an exact multiple of the curve width?
   There is a rather simple `pict2e` based example in the manual, but a fully flexible curvy underline seems like a package of it's own.

More generally, if you have good ideas about often needed constructs and reasonable parameters for them, it might be a good idea to write a higher level package using `lua-ul` as a base to provide a variety of under-*something* options.

**Comment by Mikachu2333** [comment]
Thanks for answering!
